### ISSUE TITLE
What goes in the "Write a Question" prompt for task list lessons?

### ISSUE THREAD

**Issue by doctortheisen** [TrainABA/segments#5]
***This comment contains a detailed rationale and philosophy supporting the "Write a Question" prompt issue. The comment below is a reply to this post and has a shorter rationale.***

The TrainABA books for Independent Fieldwork contain a box/writing prompt, labeled, "Questions to Ask Your Supervisor." What is the point of this box? It was not explained well in the books and no examples/non-examples of what to write in that box were provided in the book.

That problem was not very noticeable in the books because supervisors using books met with learners face-to-face. The learner could hand the book to the supervisor. Bad questions (sidebar/off-topic conversations, vague/ambiguous questions, etc.) were easily resolved by the supervisor taking a conversational approach to answering the question. For example,

SCENARIO 1

Setting: Supervision meeting, individual format, at a client session.
SUPERVISOR: Let me see your book, for questions.
LEARNER: Here you go.
(BOOK content reads: "Why is this item on the task list? Isn't it something we don't really do in the field?")
SUPERVISOR: Okay, I see. So are you wondering how this task list item could actually be used in the field?
LEARNER: Exactly.

The above conversation would turn into a brainstorming session. It might end up being a productive supervisor/learner interaction, though that may be more about the individual attention of having a conversation than any important insights resulting from casual brainstorming. SCENARIO 1 does not work for an online learning platform submission, because there will not be a back-and-forth exchange that evolves into a question. The question needs to be a targeted, portable, clear question that supplies relevant context and can be answered in a way that solves the problem.

Here is a second scenario for an individual supervisory contact meeting, in real life, in which a learner asks the supervisor a question.

SCENARIO 2
LEARNER: Hey, so what about how we just saw the uncle reinforce that behavior. Is that what we are talking about with this task list item?
SUPERVISOR: Oh, wow. Yeah, I'm impressed you caught that. You are right. Tell me more about that...

The above situation would not work for online learning platforms. Some of the best learning opportunities occur naturally in the environment, as we all know. For a technical question on the learning platform, questions should be planned. The best questions present a distilled problem, supply the necessary information (without privacy violations of ANY kind), are portable, clear, and can be answered in a way that solves the problem. 

What is "portability" in a technical question, and why does that matter?
If a question is asked well, another person who is not familiar with the person asking or their actual situation can answer the question. Another person who has a similar question can find the question in an online search and see an answer that may work. Good technical questions and answers promote a professional online community. Social media groups are not appropriate for such conversations because the content is not strongly moderated.

Whether for intranet, extranet, internet q&a sites, or just a text to a supervisor, the skill of articulating questions in writing is highly important to ABA practitioners. The more practice supervisors have, the better they can model and assist technicians in writing technical questions. These questions can indirectly benefit the client, as well as other practitioners and technicians in the future when ABA has a better resource for a q&a site with appropriate privacy and moderation skills.

The final decision for version 2.0.0 of the TrainABA Moodle Supervision LMS course is to include the prompt, "Write a Question," and expect learners to deliver something that works in print. A casual question or vague discussion that leads to brainstorming is not acceptable. The skill is important and we stand by it.

**Comment by purr-diesel** [comment]
Rationale for requesting that learners practice writing clear, concise questions: 

In any technical field, distilling ideas down to a clear, focused inquiry is a valuable skill. Issues phrased as questions can be answered, allowing the problem to be solved. The clearer the question, the more easily it can be understood by others. 

It is also easier for you to understand when returning to the question months later, after forgetting much of the relevant context you knew when asking the question. Lastly, supervisors who practice this skill can model it for technicians, resulting in better team communication that is more portable and lasts longer than issues addressed in a less systematic, technical way.

**Comment by purr-diesel** [comment]
Examples for Topic of "Negative Reinforcement"

Good question

- "What can I try as a supervisor when the ABA program uses positive reinforcement, but the technicians say the client's parents rely on negative reinforcement and bribes?"

Problem questions

- Idiosyncratic question: "How come we are not supposed to use negative reinforcement with client MITU, when that was goal #3 of her IEP report?"
- Off-topic question: "How can I use negative reinforcement to get a raise at this company?"
- Open-ended question: "What's an example of negative reinforcement at work setting for the company, not just with a client?"

**Comment by doctortheisen** [comment]
Okay @purr-diesel that looks good. We'll cut rationale and examples from that Moodle page template to clean it up. 

Look for redundant language and delete the extra text (don't post it here).

**Comment by purr-diesel** [comment]
Tips for Learners to Write A Good Question

- Your moderator may not be able to an answer unclear or vague questions
- Do not ask a question about client-specific or idiosyncratic issues that only your supervisor would know, as someone else may moderate this post at some point in the future.

**Comment by purr-diesel** [comment]
Tips for Moderators

- Read these questions before meetings and address them at supervisory contacts.
- For group meetings, use practical questions as scenarios for BST trainings.
- For individual meetings, use questions as starting point to assess using performance measures in the TrainABA Reference Manual (written on each task list item). Time is limited for supervision, so a small time hack like this can help.
